#!/bin/bash

mkdir -p build
cd build
cmake .. -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_EXAMPLES=OFF -DNATS_BUILD_LIB_SHARED=OFF -DNATS_BUILD_OPENSSL_STATIC_LIBS=ON \
-DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_CLOUD_CLIENT=OFF